### ISSUE TITLE
Crasher

### ISSUE THREAD

**Issue by svendsvin** [ejvindh/AndGro#1]
Er måske ikke kompertibel med Android 10? Den crasher i hvert fald hver gang jeg trykker på noget i appen. Ellers en glimrende ide.

**Comment by ejvindh** [comment]
Jeg kører selv stadig rundt med nogle af de ældre android devices, så helt ærligt, så ved jeg det ikke. Men jeg vil gerne engang ved lejlighed undersøge sagen.

**Comment by svendsvin** [comment]
Tak for det. Her er en fejllog. Måske du kan få noget ud af den:

java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at com.ejvindh.andgro.MainActivity.show_results(MainActivity.java:286)
	at com.ejvindh.andgro.MainActivity.onClick(MainActivity.java:454)
	at android.view.View.performClick(View.java:7185)
	at android.widget.CompoundButton.performClick(CompoundButton.java:142)
	at android.view.View.performClickInternal(View.java:7162)
	at android.view.View.access$3500(View.java:819)
	at android.view.View$PerformClick.run(View.java:27684)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by ejvindh** [comment]
Lige inden jeg kommer alt for langt, så tænker jeg med den fejlmelding på, om du er sikker på, at du har fået lagt databasefilerne i den mappe, som jeg beskriver i vejledningen?

**Comment by ejvindh** [comment]
Nå, nu besvarer jeg lige selv mit spørgsmål, idet jeg nu har prøvet at køre programmet på en virtuel Android11, og da jeg startede Appen uden ordbøger lagt ind, fik jeg samme fejl, som du fortæller om her. Men efter at jeg havde lagt ordbøger ind på maskinen, og indstillet appen til at kunne finde dem, virkede det fint.

Så medmindre du kan tilføje mere, regner jeg med at appen virker helt op til Android11 :)

**Comment by svendsvin** [comment]
Bekræftet. Den virker også på Android 10. Min Xiaomi sætter alle nye apps i dark mode, hvilket alle apps ikke er klar til (AndGro er ikke). Da jeg fik det ændret kunne jeg også læse hvad der stod i menuen. Tak for opklaringen og en genial app.

**Comment by ejvindh** [comment]
Super. Godt du fik det til at virke.

**Comment by svendsvin** [comment]
Hej Ejvindh

Tak for din app. Den er super hjælpsom. Jeg har skiftet til android 11 og får en fejlmeddelelse fra google når jeg installerer. Appen fungerer som den skal, men den fylder ikke hele skærmen. Har du mulighed for at opdatere din app så den kører optimalt på android 11/12? Det vil være fantastisk.

Mvh. Svend
________________________________
Fra: ejvindh ***@***.***>
Sendt: 7. december 2020 20:55
Til: ejvindh/AndGro ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [ejvindh/AndGro] Crasher (#1)


Super. Godt du fik det til at virke.

**Comment by ejvindh** [comment]
Hmm, jeg kører selv med Android 12 nu, og her ser alt fint ud. Hvilket device bruger du, og har du mulighed for at fortælle hvordan fejlen Lyder fra Google. Kører du med høj eller bred display?

**Comment by svendsvin** [comment]
Tak for svar. Fejlen er noget med, at app'en ikke passer til systemet og jeg skal kontakte udvikleren for at høre om en opdatering. Jeg kan dog godt installere. GUIen fylder ikke hele skærmen kun ca. 7/10. Jeg har løst det ved at tillade appen at være i fuld skærm. Igen tak for responsen og din hjælpsomme app. Og beklager ulejligheden.
________________________________
Fra: ejvindh ***@***.***>
Sendt: 30. juli 2022 12:16
Til: ejvindh/AndGro ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [ejvindh/AndGro] Crasher (#1)


Hmm, jeg kører selv med Android 12 nu, og her ser alt fint ud. Hvilket device bruger du, og har du mulighed for at fortælle hvordan fejlen Lyder fra Google. Kører du med høj eller bred display?

**Comment by ejvindh** [comment]
Ok. Jeg har også fået kigget lidt videre på det, og kan nu se, at hvis jeg lægger min telefon ned, så ser det også forkert ud. Hos mig er appen så bare for stor til at være på skærmen. Det vil jeg ved lejlighed prøve at se på, om jeg kan få fixet. Men jeg fornemmer at det ikke er en akut ting for dig heller, så det bliver ikke lige det allerførste, jeg går i gang med her efter ferien. Men den er lagt i pipen, så der skal nok komme til at ske noget.

**Comment by ejvindh** [comment]
Nu har jeg givet et bud på et bedre design til landscape-devices. Jeg håber det fungerer bedre for dig. Du finder den nye version her: https://github.com/ejvindh/AndGro/releases/tag/v1.3

**Comment by svendsvin** [comment]
Spændende, men jeg får ikke lov at installere. Giver fejl om filtype ikke kan installeres.
________________________________
Fra: ejvindh ***@***.***>
Sendt: 6. august 2022 22:52
Til: ejvindh/AndGro ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [ejvindh/AndGro] Crasher (#1)


Nu har jeg givet et bud på et bedre design til landscape-devices. Jeg håber det fungerer bedre for dig. Du finder den nye version her: https://github.com/ejvindh/AndGro/releases/tag/v1.3

**Comment by ejvindh** [comment]
Det var underligt. Er det apk-filen, du henter? Altså denne:
https://github.com/ejvindh/AndGro/releases/download/v1.3/AndrGro.apk

Og har du husket at slå til, at du gerne vil installere fra usikre kilder?

**Comment by svendsvin** [comment]
2x ja. Jeg har prøvet adskillige gange men samme resultat hver gang.
________________________________
Fra: ejvindh ***@***.***>
Sendt: 7. august 2022 11:10
Til: ejvindh/AndGro ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [ejvindh/AndGro] Crasher (#1)


Det var underligt. Er det apk-filen, du henter? Altså denne:
https://github.com/ejvindh/AndGro/releases/download/v1.3/AndrGro.apk

Og har du husket at slå til, at du gerne vil installere fra usikre kilder?

**Comment by svendsvin** [comment]
Hmm... har lige prøvet at installere på min arbejdstelefon. Det gik fint. Må lige se min privattelefon igennem igen.
________________________________
Fra: ejvindh ***@***.***>
Sendt: 7. august 2022 11:10
Til: ejvindh/AndGro ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [ejvindh/AndGro] Crasher (#1)


Det var underligt. Er det apk-filen, du henter? Altså denne:
https://github.com/ejvindh/AndGro/releases/download/v1.3/AndrGro.apk

Og har du husket at slå til, at du gerne vil installere fra usikre kilder?

**Comment by svendsvin** [comment]
Det er mærkeligt. Efter jeg har svaret på om jeg stadig vil installere fra usikker kilde i min privat telefon får jeg at vide appen ikke er installeret. Men den fungerer i landscape og jeg skal ikke bruge fuld skærm i indstillinger længere. Men når jeg ser i appens indstillinger er det stadig version 1.0.
________________________________
Fra: ejvindh ***@***.***>
Sendt: 7. august 2022 11:10
Til: ejvindh/AndGro ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [ejvindh/AndGro] Crasher (#1)


Det var underligt. Er det apk-filen, du henter? Altså denne:
https://github.com/ejvindh/AndGro/releases/download/v1.3/AndrGro.apk

Og har du husket at slå til, at du gerne vil installere fra usikre kilder?

**Comment by ejvindh** [comment]
Hmja, det kan jeg ikke helt forklare. Men du kan jo enten stille dig tilfreds med at det virker som det skal. Eller du kan prøve helt at afinstallere den, og så nyinstallere fra bunden. Måske det løser det...
